# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "A Fine Romance"
style = "Jazz"
composer = "Jerome Kern"
poet = "Dorothy Fields"
piece = "Moderately"
copyright = "1936 T.B. Harms Company. Copyright Renewed."
copyrightextra = "(c/o The Welk Music Group, Santa Monica, CA 90401)."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "7c9691e6-a26e-11df-8418-0019d11e5a41"
structure = "ABAC"
structureremark = "the structure of this tune can also be AA or AA'. Doesn't really matter."
location = "rbk1:3,jfb:116"
idyoutuberemark1 = "Oscar Peterson!"
idyoutube1 = "ytipqjANlrY"
idyoutuberemark2 = "Ella and Louis, great vocal performance of this song"
idyoutube2 = "cKbD4PQBrIA"
lyricsurl = "http://www.elyrics.net/read/b/billie-holiday-lyrics/a-fine-romance-lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1936 T.B. Harms Company. Copyright Renewed."
fullpoet = "Lyrics by Dorothy Fields"
fullcomposer = "Music by Jerome Kern"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
