# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "All The Things You Are"
style = "Jazz"
subtitle = "From 'Very Warm For May'"
composer = "Jerome Kern"
poet = "Oscar Hammerstein II"
piece = "Moderately"
copyright = "1939 T.B. Harms Company. Copyright Renewed."
copyrightextra = "(c/o The Welk Music Group, Santa Monica, CA 90401)"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "a064f20e-fb85-11e0-8d5d-0019d11e5a41"
structure = "ABC"
location = "rbk1:18,jfb:40"
idyoutuberemark1 = "Charlie Parker, great performance"
idyoutube1 = "UTORd2Y_X6U"
idyoutuberemark2 = "Art Tatum. Brilliant"
idyoutube2 = "_bPgf_olXeE"
lyricsurl = "http://www.lyrics007.com/Jerome%20Kern%20Lyrics/All%20The%20Things%20You%20Are%20Lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "All The Things You Are / Jerome Kern, Oscar Hammerstein II"
copyright = "Copyright © 1939 T.B. Harms Company. Copyright Renewed."
fullpoet = "Lyrics by Oscar Hammerstein II"
fullcomposer = "Music by Jerome Kern"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
