# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "All Of Me"
style = "Jazz"
composer = "Seymour Simons, Gerald Marks"
poet = "Seymour Simons, Gerald Marks"
piece = "Mod. Swing"
copyright = "1931 Bourne Co. Copyright Renewed"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "6dd0233c-03b8-11e1-b5a9-0019d11e5a41"
structure = "AB"
structureremark = "the structure of this tune could also be interpreted as ABAC since the 8 first bars of A and B are the same."
location = "rbk1:16,jfb:39"
idyoutuberemark1 = "Louis Armstrong with amazing rythm"
idyoutube1 = "wFzxo-XI8As"
idyoutuberemark2 = "Ella Firtzerald - amazing"
idyoutube2 = "Mx5b4AFVaT8"
idyoutuberemark3 = "Oscar - amazing version"
idyoutube3 = "aNLvaBCFHdE"
lyricsurl = "http://www.lyrics007.com/Frank%20Sinatra%20Lyrics/All%20Of%20Me%20Lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = true
idyoutube3 = true
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1931 Bourne Co. Copyright Renewed"
fullcomposer = "Lyrics and Music by Seymour Simons, Gerald Marks"
fullpoet = ""

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
