# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "TBK"

[attributes]
title = "Always"
style = "Jazz"
composer = "Irving Berlin"
poet = "Irving Berlin"
piece = "Waltz"
copyright = "1925 (Renewed) by Irving Berlin"
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "e2f7709c-da80-11e3-80dc-7f255b43b3a5"
structure = "AB"
structureremark = "The tune has an ABAC feel to it because the A and B part start off the same way"
location = "tbk:354"
idyoutuberemark1 = "Frank!"
idyoutube1 = "eLh-m1Z_feY"
idyoutuberemark2 = "Billie!"
idyoutube2 = "iQPdnqDAJE4"
lyricsurl = "http://www.metrolyrics.com/always-lyrics-irving-berlin.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Always / Irving Berlin"
copyright = "Copyright © 1925 (Renewed) by Irving Berlin"
fullcomposer = "Lyrics and Music by Irving Berlin"
fullpoet = ""

[versions.TBK]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
