# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Angel Eyes"
style = "Jazz"
composer = "Matt Dennis"
poet = "Earl Brent"
piece = "Slow Blues"
copyright = "1946 (Renewed 1973) Dorsey Brothers Music"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "0a43bee4-e044-11e3-9617-b76a2faa3d0b"
structure = "AABA"
location = "jfb:45"
idyoutuberemark1 = "Chet Baker in a very good version"
idyoutube1 = "shuy1hpUGvQ"
idyoutuberemark2 = "Stings version (I like this one...)"
idyoutube2 = "QS1MgqJ7B3Y"
lyricsurl = "http://www.metrolyrics.com/angel-eyes-lyrics-ella-fitzgerald.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1946 (Renewed 1973) Dorsey Brothers Music"
fullpoet = "Lyrics by Earl Brent"
fullcomposer = "Music by Matt Dennis"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
