# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Aebersold"

[attributes]
title = "Au Privave"
style = "Jazz"
composer = "Charlie Parker"
piece = "Upbeat Swing"
copyright = "1956, Atlantic Music Corp."
copyrightextra = "1978, Atlantic Music Corp."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "e62b60ec-eb9b-11e0-aab7-0019d11e5a41"
structure = "Blues"
location = "rbk1:32,jfb:50,file:au_privave_omnibook.pdf"
idyoutube1 = "HUNgcPSYeyM"
idyoutube2 = "dvdQYSWOobc"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1956, Atlantic Music Corp."
fullpoet = ""
fullcomposer = "Music by Charlie Parker"

[versions.Aebersold]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
