# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Autumn In New York"
style = "Jazz"
composer = "Vernon Duke"
poet = "Vernon Duke"
piece = "Brightly"
copyright = "1934 by Kay Duke Music."
copyrightextra = "Copyright Renewed. All Rights Administered by BMG Songs, Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "9677b522-7463-11e1-a57d-bbc28ffad085"
structure = "ABAC"
structureremark = "I determined it was ABAC although the part A does not repeat exactly. It is good enough"
location = "rbk1:33,hlrjb:34"
idyoutuberemark1 = "Virtuoso Sonny Stitt"
idyoutube1 = "Nn11v07Db3s"
idyoutuberemark2 = "The classic Billie Holiday..."
idyoutube2 = "cl_e7UW-bz8"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Autumn-in-New-York-lyrics-Frank-Sinatra/C779DB117665DFD94825691F00067AD0"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Autumn In New York / Vernon Duke"
copyright = "Copyright © 1934 by Kay Duke Music."
fullcomposer = "Lyrics and Music by Vernon Duke"
fullpoet = ""

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
