# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Beautiful Love"
style = "Jazz"
composer = "Victor Young, Wayne King, Egbert Vanalstyne, Haven Gillespie"
piece = "Ballad"
copyright = "1931 and 1959 Movietone Music Corporation, New York, New York"
copyrightextra = "Copyright Renewed"
typesetter = "Roberto Bucher <roberto.bucher@sunrise.ch>"
completion = "5"
uuid = "b15e533d-b59f-4db6-b363-b716a6b7b161"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1931 and 1959 Movietone Music Corporation, New York, New York"
fullpoet = ""
fullcomposer = "Music by Victor Young, Wayne King, Egbert Vanalstyne, Haven Gillespie"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
