# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Bewitched"
style = "Jazz"
composer = "Richard Rodgers"
poet = "Lorenz Hart"
piece = "Moderately Slow"
copyright = "1941, by Chappell & Co., Inc. Copyright Renewed"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "dd1624e6-2567-11e1-9444-0019d11e5a41"
structure = "AABA"
location = "rbk2:43,jfb:58"
idyoutuberemark1 = "Ella Fitzgerald with the intro part..."
idyoutube1 = "nDlCCKHql0w"
idyoutuberemark2 = "Benny Goodman in the 1980's"
idyoutube2 = "rv8G78Cw2mc"
lyricsurl = "http://www.lyricsfreak.com/e/ella+fitzgerald/bewitched_20045684.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1941, by Chappell & Co., Inc. Copyright Renewed"
fullpoet = "Lyrics by Lorenz Hart"
fullcomposer = "Music by Richard Rodgers"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
