# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Blue Monk"
style = "Jazz"
composer = "Thelonius Monk"
piece = "Blues"
copyright = "1962 (Renewed 1990) by Thelonious Monk Corp."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "4cc04ec0-e8b6-11e3-a334-5bb66fd360f0"
structure = "A"
location = "rbk1:54"
idyoutuberemark1 = "Classic Monk..."
idyoutube1 = "FRUWtrgTpcs"
idyoutuberemark2 = "Bobby McFerrin and Chick Corea"
idyoutube2 = "u0LDlgOsp_k"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Blue Monk / Thelonius Monk"
copyright = "Copyright © 1962 (Renewed 1990) by Thelonious Monk Corp."
fullpoet = ""
fullcomposer = "Music by Thelonius Monk"

[versions.Real]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
