# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Blue Skies"
style = "Jazz"
composer = "Irving Berlin"
poet = "Irving Berlin"
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "fe14b29a-da80-11e3-a178-07c25bb937a6"
structure = "AABA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = false
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Blue Skies / Irving Berlin"
copyright = "-- help me fill it out this copyright notice --"
fullcomposer = "Lyrics and Music by Irving Berlin"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
