# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Blue Bossa"
style = "Jazz"
composer = "Kenny Dorham"
poet = "Joan Cartwright"
piece = "Bossa Nova"
copyright = "1965 (Renewed 1993) Second Floor Music"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "f7fdc5e0-db41-11e0-a31c-0019d11e5a41"
structure = "A"
location = "rbk1:51"
remark = "Play last 4 bars twice more to end"
idyoutube1 = "EhQfGODnvww"
idyoutube2 = "-0mNSP1452o"
idyoutube3 = "6sr7BXinJMw"
idyoutube4 = "lKEEVECH58Q"
lyricsurl = "http://fyicomminc.bizland.com/music/lyrics/bluebossa.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = true
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = true
idyoutuberemark4 = false
idyoutube4 = true
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Blue Bossa / Kenny Dorham, Joan Cartwright"
copyright = "Copyright © 1965 (Renewed 1993) Second Floor Music"
fullpoet = "Lyrics by Joan Cartwright"
fullcomposer = "Music by Kenny Dorham"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = true
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
