# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Body And Soul"
style = "Jazz"
composer = "John Green"
poet = "Edward Heyman, Robert Sour, Frank Eyton"
piece = "Slowly, with expression"
copyright = "1930 Warner Bros. Inc & Chappell & Co. Ltd."
copyrightextra = "Copyright Renewed & Assigned to Warner Bros. Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "b2076c06-e025-11e0-ab4c-0019d11e5a41"
structure = "AABA"
location = "rbk1:59,jfb:67"
idyoutuberemark1 = "Billie Holiday"
idyoutube1 = "CMDlk6lGQOk"
idyoutuberemark2 = "Dexter Gordon from the ballads. Excellent"
idyoutube2 = "rMd9oZ4O0bs"
lyricsurl = "http://www.azlyrics.com/lyrics/dianakrall/bodyandsoul.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1930 Warner Bros. Inc & Chappell & Co. Ltd."
fullpoet = "Lyrics by Edward Heyman, Robert Sour, Frank Eyton"
fullcomposer = "Music by John Green"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = true
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
