# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "But Beautiful"
style = "Jazz"
composer = "Johnny Burke, James Van Heusen"
poet = "Johnny Burke, James Van Heusen"
piece = "Slowly"
copyright = "1947 by Doesey Brothers Music, A Division of Music Sales Corporation, New York"
copyrightextra = "Copyright Renewed"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "769f56f4-7f33-11ea-b0b2-eb3dd252214d"
structure = "ABAC"
structureremark = ""
location = "jfb:74"
idyoutuberemark1 = "Tony Bennett and Lady Gaga"
idyoutube1 = "O1OdWOLWeCM"
idyoutuberemark2 = "Classic Nat King Cole version"
idyoutube2 = "uywr_l2tfdQ"
lyricsurl = "https://genius.com/Nat-king-cole-but-beautiful-lyrics"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1947 by Doesey Brothers Music, A Division of Music Sales Corporation, New York"
fullcomposer = "Lyrics and Music by Johnny Burke, James Van Heusen"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
