# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "But Not For Me"
style = "Jazz"
composer = "George Gershwin"
poet = "Ira Gershwin"
piece = "Moderately"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "c05b953a-3034-11e5-b197-3860779cb560"
structure = "ABAC"
structureremark = "This is almost an A tune since the B and C in the ABAC interpretation are almost the same"
location = "rbk2:50"
idyoutuberemark1 = "A great version by Miles Davis and Sonny Rollins"
idyoutube1 = "r98HGV9M7SY"
idyoutuberemark2 = "A classic version of Ella Fitzgerald"
idyoutube2 = "FnfUN6bBAg4"
lyricsurl = "http://www.azlyrics.com/lyrics/ellafitzgerald/butnotforme.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "-- help me fill it out this copyright notice --"
fullpoet = "Lyrics by Ira Gershwin"
fullcomposer = "Music by George Gershwin"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
