# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Desafinado"
style = "Jazz"
subtitle = "Slightly Out Of Tune"
composer = "Antonio Carlos Jobim"
poet = "Newton Mendonca, Jon Hendricks, Jessie Cavanaugh"
piece = "Medium Bossa Nova"
copyright = "1959 and 1962, Editora Musical Arapua, Sao Paulo, Brazil"
copyrightextra = "1959 1962, Editora Musical Arapua, Sao Paulo, Brazil"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "c3fff540-a26e-11df-9435-0019d11e5a41"
structure = "AABA"
location = "rbk1:112-113,jfb:97"
idyoutuberemark1 = "Joao Gilberto in a nice brasilian version"
idyoutube1 = "g6w3a2v_50U"
idyoutuberemark2 = "Stan Getz in a nice instrumental version"
idyoutube2 = "lo1SiVwVqic"
lyricsurl = "http://www.hotlyrics.net/lyrics/E/Ella_Fitzgerald/Desafinado.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1959 and 1962, Editora Musical Arapua, Sao Paulo, Brazil"
fullpoet = "Lyrics by Newton Mendonca, Jon Hendricks, Jessie Cavanaugh"
fullcomposer = "Music by Antonio Carlos Jobim"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
