# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Donna Lee"
style = "Jazz"
composer = "Charlie Parker"
piece = "Up Tempo"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "a9ca1752-53d6-11e2-a687-1bd4487b8eae"
structure = "AB"
structureremark = "This could be thought of as ABAC although the two A's are not the same so AB is more accurate"
location = "rbk1:124"
idyoutuberemark1 = "Very fast Wynton Marsalis version"
idyoutube1 = "QdD6XE9DtAE"
idyoutuberemark2 = "The original Parker, Davis, Bud Powell version"
idyoutube2 = "hANODMX9c5g"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "-- help me fill it out this copyright notice --"
fullpoet = ""
fullcomposer = "Music by Charlie Parker"

[versions.Real]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
