# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Don't Explain"
style = "Jazz"
composer = "Billie Holiday"
poet = "Arthur Herzog, Jr."
piece = "Slowly"
copyright = "1946 by Northern Music Company"
copyrightextra = "Rights Administered by MCA Music Publishing, A Division of MCA INC., New York, NY. Copyright Renewed."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "070df83e-0676-11e1-b7fe-0019d11e5a41"
structure = "AABA"
location = "jfb:102,jltd:90"
idyoutuberemark1 = "Billie in a radio show"
idyoutube1 = "XxwJ9lh-id4"
idyoutuberemark2 = "The great Dexter Gordon at the height of his power"
idyoutube2 = "k2Lx3n10fkc"
lyricsurl = "http://www.elyrics.net/read/b/billie-holiday-lyrics/don_t-explain-lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Don't Explain / Billie Holiday, Arthur Herzog, Jr."
copyright = "Copyright © 1946 by Northern Music Company"
fullpoet = "Lyrics by Arthur Herzog, Jr."
fullcomposer = "Music by Billie Holiday"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
