# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Easy Living"
style = "Jazz"
composer = "Ralph Rainger, Leo Robin"
poet = "Ralph Rainger, Leo Robin"
piece = "Med"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "c5019d6a-88cc-11e4-8336-3860779cb560"
structure = "AABA"
location = "rbk1:129"
idyoutuberemark1 = "Ella Fitzgerald with Joe Pass on Guitar"
idyoutube1 = "6vYIHpxuxp4"
idyoutuberemark2 = "The incredible Bill Evans"
idyoutube2 = "T0ZwAJAgBFM"
lyricsurl = "http://www.lyricsfreak.com/b/billie+holiday/easy+living_20017912.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "-- help me fill it out this copyright notice --"
fullcomposer = "Lyrics and Music by Ralph Rainger, Leo Robin"
fullpoet = ""

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
