# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Gentle Rain"
style = "Jazz"
composer = "Louis Bonfa"
poet = "Matt Dubey"
piece = "Bossa"
copyright = "1931 (renewed 1959) EMI Robbins Catalog, Inc"
copyrightextra = "Used by Persmission of CPP/Belwin, Inc, Miami, FL. International Copyright Secured. All Rights Reserved."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "04bbfb74-0128-11e1-9e2a-0019d11e5a41"
structure = "AB"
structureremark = "This tune has a weird structure because the part B has different lengths"
location = "rbk1:169,nrbk3:128"
idyoutuberemark1 = "Tony Bennet slow version"
idyoutube1 = "uJGqzudEDDE"
idyoutuberemark2 = "The wonderful ballad version of Astrud Gilberto"
idyoutube2 = "s6ndU7GKpjI"
lyricsurl = "http://lyrics.wikia.com/Astrud_Gilberto:The_Gentle_Rain"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1931 (renewed 1959) EMI Robbins Catalog, Inc"
fullpoet = "Lyrics by Matt Dubey"
fullcomposer = "Music by Louis Bonfa"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
