# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Gloria's Step"
style = "Jazz"
composer = "Scott LaFaro"
piece = "Swing"
copyright = "1962, Orpheum Music."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "892e5552-f2ad-11e0-8c10-0019d11e5a41"
structure = "AABA"
location = "rbk1:172,nrbk1:118"
idyoutuberemark1 = "Bill Evans, not the orignal Sunday at the Village version..."
idyoutube1 = "C84KmJwtPeI"
idyoutuberemark2 = "the original Sunday at the Village version (take 2)..."
idyoutube2 = "Aib_RL_x7PA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1962, Orpheum Music."
fullpoet = ""
fullcomposer = "Music by Scott LaFaro"

[versions.Real]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
