# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Green Dolphin Street"
style = "Jazz"
composer = "Bronislau Kaper"
poet = "Ned Washington"
piece = "Latin/Swing"
copyright = "1947 (Renewed 1975) MGM/EMI Feist Catalog, Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "b93bdc7e-0207-11e1-9e68-0019d11e5a41"
structure = "ABAC"
location = "rbk1:179,tbk:227,gt:126,nrbk3:273"
idyoutuberemark1 = "Sarah Vaughan from a radio show"
idyoutube1 = "vHp0IvAEFMQ"
idyoutuberemark2 = "The great Coltrane"
idyoutube2 = "Ny1n5E4IdYY"
lyricsurl = "http://www.lyricszoo.com/miles-davis/on-green-dolphin-street-miles-davis-washington-ned/"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1947 (Renewed 1975) MGM/EMI Feist Catalog, Inc."
fullpoet = "Lyrics by Ned Washington"
fullcomposer = "Music by Bronislau Kaper"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
