# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Guilty"
style = "Jazz"
composer = "Gus Kahn, Harry Akst, Richard A. Whiting"
poet = "Gus Kahn, Harry Akst, Richard A. Whiting"
piece = "Slowly"
copyright = "1931 (Renewed 1958) Whiting Publishing and EMI Feist Catalog Inc."
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "16154c88-da81-11e3-b38d-b75a4937af0f"
structure = "AABA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Guilty / Gus Kahn, Harry Akst, Richard A. Whiting"
copyright = "Copyright © 1931 (Renewed 1958) Whiting Publishing and EMI Feist Catalog Inc."
fullcomposer = "Lyrics and Music by Gus Kahn, Harry Akst, Richard A. Whiting"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
