# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "How High The Moon"
style = "Jazz"
composer = "Morgan Lewis"
poet = "Nancy Hamilton"
piece = "Moderately"
copyright = "1940 by Chappell & Co., Inc. Copyright Renewed."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "7d17fd1c-15fe-11e1-b205-0019d11e5a41"
structure = "AB"
structureremark = "this tunes structure can also be categorised as ABAC if you take the AB as A and the AC as B. Under the AB interpretation the first part of A (first 8 bars) is the same as the first part of B."
location = "rbk1:202,jfb:149"
idyoutuberemark1 = "Ella!"
idyoutube1 = "2d-l7_TGnIE"
idyoutuberemark2 = "Grappelli in a nice emotional version with McCoy Tyner at the Piano"
idyoutube2 = "S4kf5aU1Wtg"
lyricsurl = "http://www.lyricsfreak.com/e/ella+fitzgerald/how+high+the+moon_20045644.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1940 by Chappell & Co., Inc. Copyright Renewed."
fullpoet = "Lyrics by Nancy Hamilton"
fullcomposer = "Music by Morgan Lewis"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
