# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "I Could Have Danced All Night"
style = "Jazz"
subtitle = "From 'My Fair Lady'"
composer = "Frederick Loewe"
poet = "Alan Jay Lerner"
piece = "Moderately"
copyright = "1956 by Alan Jay Lerner & Frederick Loewe. Copyright Renewed"
copyrightextra = "Chappell & Co., Inc., owner of publication and allied rights throughout the World"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "47321f34-1a2e-11e4-b94f-232e14538fbe"
structure = "ABCD"
structureremark = "A, B and D parts are similar in many ways but not in exact harmony so this tune is close to a an AABA tune."
location = "jfb:153"
idyoutuberemark1 = "Frank in a great version"
idyoutube1 = "IGqGBu6Ksqk"
idyoutuberemark2 = "Julie Andrews in a musical like version"
idyoutube2 = "JNaIor5lxN8"
lyricsurl = "http://www.metrolyrics.com/i-could-have-danced-all-night-lyrics-my-fair-lady.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "I Could Have Danced All Night / Frederick Loewe, Alan Jay Lerner"
copyright = "Copyright © 1956 by Alan Jay Lerner & Frederick Loewe. Copyright Renewed"
fullpoet = "Lyrics by Alan Jay Lerner"
fullcomposer = "Music by Frederick Loewe"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
