# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "I Could Write A Book"
style = "Jazz"
subtitle = "From 'Pal Joey'"
composer = "Richard Rodgers"
poet = "Lorenz Hart"
piece = "Ballad"
copyright = "1940, Chappell & Co., Inc. Copyright Renewed."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "e00ddbf8-a26e-11df-92da-0019d11e5a41"
structure = "ABAC"
structureremark = "could be categorized as AB"
location = "rbk1:209,jfb:153"
idyoutuberemark1 = "Frank in the classic vocal version"
idyoutube1 = "UwoZNHhFgLQ"
idyoutuberemark2 = "Miles swings!"
idyoutube2 = "_DH46QyK2cw"
lyricsurl = "http://www.lorenzhart.org/booksng.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1940, Chappell & Co., Inc. Copyright Renewed."
fullpoet = "Lyrics by Lorenz Hart"
fullcomposer = "Music by Richard Rodgers"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
