# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "I Don't Want To Set The World On Fire"
style = "Jazz"
composer = "Eddie Seiler, Sol Marcus, Bennie Benjamin"
poet = "Eddie Seiler, Sol Marcus, Bennie Benjamin"
piece = "Moderately"
copyright = "1940 by Bergman, Vocco, & Conn, Inc."
copyrightextra = "Copyright Renewed, Benjamin & Marcus interests assigned to Bennie Benjamin Music, Inc. (Intersong Music, Publisher)"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "5a3efd64-70b7-11e5-bcb5-3860779cb560"
structure = "AABA"
location = "jfb:156"
idyoutuberemark1 = "Fats Domino classic version"
idyoutube1 = "olF-OnbDM3w"
idyoutuberemark2 = "Betty Carter version"
idyoutube2 = "gbDYyzvc9Kc"
lyricsurl = "http://www.lyricsmode.com/lyrics/t/the_ink_spots/i_dont_want_to_set_the_world_on_fire.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1940 by Bergman, Vocco, & Conn, Inc."
fullcomposer = "Lyrics and Music by Eddie Seiler, Sol Marcus, Bennie Benjamin"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
