# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "I'll Remember April"
style = "Jazz"
composer = "Don Raye, Gene De Paul, Pat Johnson"
poet = "Don Raye, Gene De Paul, Pat Johnson"
piece = "Moderately"
copyright = "1941, 1942 by MCA Music Publishing, A Division of MCA, Inc."
copyrightextra = "Renewed 1969, 1970 Pic Corp."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "84142766-dba0-11e3-9e62-bb6aa0505531"
structure = "ABA"
location = "jfb:168-169"
idyoutuberemark1 = "Caterina Valente & Chet Baker"
idyoutube1 = "2YZ4FGEGom8"
idyoutuberemark2 = "Sonny Stitt blasts away..."
idyoutube2 = "VHbwr4ieI2U"
lyricsurl = "http://www.lyricsfreak.com/f/frank+sinatra/ill+remember+april_20055817.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1941, 1942 by MCA Music Publishing, A Division of MCA, Inc."
fullcomposer = "Lyrics and Music by Don Raye, Gene De Paul, Pat Johnson"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
