# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "I'm Sitting On Top Of The World"
style = "Jazz"
composer = "Ray Handerson"
poet = "Sam M. Lewis and Joel Young"
piece = "Moderately"
copyright = "1925 Leo Feist, INC."
copyrightextra = "Renewed 1953 Warock Corp."
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "8c31fdb4-da7f-11e3-ad9a-d3417ee0a02e"
structure = "AABA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1925 Leo Feist, INC."
fullpoet = "Lyrics by Sam M. Lewis and Joel Young"
fullcomposer = "Music by Ray Handerson"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
