# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Isn't It Romantic"
style = "Jazz"
subtitle = "From the Paramount Picture 'Love Me Tonight'"
composer = "Richard Rodgers"
poet = "Lorenz Hart"
piece = "Easy Swing"
copyright = "1932 (Renewed 1959) by Famous Music Corporation"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "dedcc73c-1ead-11e1-8007-0019d11e5a41"
structure = "ABAC"
location = "rbk1:238,hlrjb:181"
idyoutuberemark1 = "Cool Jazz by Chet Baker..."
idyoutube1 = "c8C6i3kpsQU"
idyoutuberemark2 = "Swinging Bill Evans..."
idyoutube2 = "10ZYoSryrcI"
lyricsurl = "http://www.stlyrics.com/lyrics/onefineday/isntitromantic.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Isn't It Romantic / Richard Rodgers, Lorenz Hart"
copyright = "Copyright © 1932 (Renewed 1959) by Famous Music Corporation"
fullpoet = "Lyrics by Lorenz Hart"
fullcomposer = "Music by Richard Rodgers"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
