# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Just Friends"
style = "Jazz"
composer = "John Klenner"
poet = "Sam M. Lewis"
piece = "Medium Swing"
copyright = "1931 (renewed 1959) EMI Robbins Catalog, Inc."
copyrightextra = "Used by by Persmission of CPP/Belwin, Inc., Miami, FL. International Copyright Secured."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "2f6e2740-f29e-11e0-9ede-0019d11e5a41"
structure = "AB"
location = "rbk1:249,nrbk3:193"
idyoutuberemark1 = "the fabulous Chet Baker"
idyoutube1 = "88CqlgFAJ-k"
idyoutuberemark2 = "fast and furious Trane"
idyoutube2 = "9W_XQCLD_I0"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Just-Friends-lyrics-Frank-Sinatra/FA2BFD6A414238734825691F000AC7E7"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1931 (renewed 1959) EMI Robbins Catalog, Inc."
fullpoet = "Lyrics by Sam M. Lewis"
fullcomposer = "Music by John Klenner"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
