# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Lullaby of birdland"
style = "Jazz"
composer = "George Shearing"
poet = "George David Weiss"
piece = "Relaxed Swing"
copyright = "1952, 1953, 1954 Adam R. Levy & Father Ent., Inc., New York NY. Copyrights Renewed."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "f9668406-a26e-11df-8542-0019d11e5a41"
structure = "AABA"
location = "rbk1:277,jfb:234"
idyoutuberemark1 = "The famous Ella version"
idyoutube1 = "UY8zK4R9oE8"
idyoutuberemark2 = "George Shearing himself! Amazing!"
idyoutube2 = "LKXvMbAKAmY"
lyricsurl = "http://www.bluesforpeace.com/lyrics/lullaby-birdland.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Lullaby of birdland / George Shearing, George David Weiss"
copyright = "Copyright © 1952, 1953, 1954 Adam R. Levy & Father Ent., Inc., New York NY. Copyrights Renewed."
fullpoet = "Lyrics by George David Weiss"
fullcomposer = "Music by George Shearing"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
