# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Moonlight in Vermont"
style = "Jazz"
composer = "Karl Suessdorf"
poet = "John Blackburn"
piece = "Freely"
copyright = "1944-1945 by MICHAEL H GOLDSEN, INC."
copyrightextra = "Renewed 1972-1973 MICHAEL H GOLDSEN, INC."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "557b082e-e0d8-11e3-a037-b365e6166d43"
structure = "AABA"
location = "jfb:256"
idyoutuberemark1 = "Louis and Ella"
idyoutube1 = "Rg0hg5YD7sE"
idyoutuberemark2 = "Franks version"
idyoutube2 = "_CiizL8Vfu8"
lyricsurl = "http://www.azlyrics.com/lyrics/franksinatra/moonlightinvermont.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Moonlight in Vermont / Karl Suessdorf, John Blackburn"
copyright = "Copyright © 1944-1945 by MICHAEL H GOLDSEN, INC."
fullpoet = "Lyrics by John Blackburn"
fullcomposer = "Music by Karl Suessdorf"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
