# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "My One And Only Love"
style = "Jazz"
composer = "Guy Wood"
poet = "Robert Mellin"
piece = "Slowly"
copyright = "1952, 1953 SHERWIN MUSIC PUBLISHING CORP."
copyrightextra = "Renewed 1980, 1981 WAROCK CORP."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "ac777f1c-0bf0-11e3-9fd3-782bcbdd3b7a"
structure = "AABA"
location = "jfb:266"
idyoutuberemark1 = "Coltrane!"
idyoutube1 = "ecrE80rnjhw"
idyoutuberemark2 = "Sting in the leaving Las-Vegas version"
idyoutube2 = "lEkJoMNFPEA"
lyricsurl = "http://www.lyricsfreak.com/l/louis+armstrong/my+one+and+only+love_20268115.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "My One And Only Love / Guy Wood, Robert Mellin"
copyright = "Copyright © 1952, 1953 SHERWIN MUSIC PUBLISHING CORP."
fullpoet = "Lyrics by Robert Mellin"
fullcomposer = "Music by Guy Wood"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
