# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "My Romance"
style = "Jazz"
subtitle = "From 'Jumbo'"
composer = "Richard Rodgers"
poet = "Lorenz Hart"
piece = "Moderately Slow"
copyright = "1935, T.B. Harms Company. Copyright Renewed, (c/o The Welk Music Group, Santa Monica, CA 90401)"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "6a5d2730-c7dd-11df-b3d0-0019d11e5a41"
structure = "ABAC"
structureremark = "this tunes song could also be noted as AB but then you lose the info that the first 8 bars of the A and part B are the same."
location = "rbk1:311,jfb:268"
idyoutuberemark1 = "Ben Webster on his airy sax..."
idyoutube1 = "_D2XBzcKFPM"
idyoutuberemark2 = "The great Bill Evans in the late 70's trio"
idyoutube2 = "aCO1Gd0jRto"
lyricsurl = "http://www.lyricsfreak.com/e/ella+fitzgerald/my+romance_20045848.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1935, T.B. Harms Company. Copyright Renewed, (c/o The Welk Music Group, Santa Monica, CA 90401)"
fullpoet = "Lyrics by Lorenz Hart"
fullcomposer = "Music by Richard Rodgers"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
