# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "My Ship"
style = "Jazz"
subtitle = "From The Musical Production 'Lady In The Dark'"
composer = "Kurt Weil"
poet = "Ira Gershwin"
piece = "Moderately Slow"
copyright = "1941 and renewed 1969 Hampshire House Publishing Corp. and Chappell & Co., Inc., New York, NY"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "ffe98a96-0a4c-11e3-bcaf-3b8eec526bc3"
structure = "AABA"
location = "jfb:268-269"
idyoutuberemark1 = "Hancock, Brecker and Hargrove"
idyoutube1 = "QTHYSBAZJrQ"
idyoutuberemark2 = "Ella and Joe Pass"
idyoutube2 = "UEOll-nNy4I"
lyricsurl = "http://www.stlyrics.com/lyrics/ladyinthedark/myship.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "My Ship / Kurt Weil, Ira Gershwin"
copyright = "Copyright © 1941 and renewed 1969 Hampshire House Publishing Corp. and Chappell & Co., Inc., New York, NY"
fullpoet = "Lyrics by Ira Gershwin"
fullcomposer = "Music by Kurt Weil"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
