# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Nice Work If You Can Get It"
style = "Jazz"
subtitle = "From 'A Damsel In Distress'"
composer = "George Gershwin"
poet = "Ira Gershwin"
piece = "Moderately"
copyright = "1937 Gershwin Publishing Corp."
copyrightextra = "Copyright Renewed, Assigned to Chappell & Co. Inc."
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "e55de2a4-da7f-11e3-8543-8726b44261b4"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Nice Work If You Can Get It / George Gershwin, Ira Gershwin"
copyright = "Copyright © 1937 Gershwin Publishing Corp."
fullpoet = "Lyrics by Ira Gershwin"
fullcomposer = "Music by George Gershwin"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
