# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Ol' Man River"
style = "Jazz"
composer = "Jerome Kern"
poet = "Oscar Hammerstein II"
piece = "Very Slowly"
copyright = "1927 T.B. Harms Company. Copyright Renewed."
copyrightextra = "(c/o The Welk Music Group, Santa Monica, CA 90401)"
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "0313b274-da80-11e3-a78b-a386f8b826fd"
structure = "AA'BA''"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Ol' Man River / Jerome Kern, Oscar Hammerstein II"
copyright = "Copyright © 1927 T.B. Harms Company. Copyright Renewed."
fullpoet = "Lyrics by Oscar Hammerstein II"
fullcomposer = "Music by Jerome Kern"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
