# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Once I Loved"
style = "Jazz"
composer = "Antonio Carlos Jobim"
poet = "Vinicius DeMoraes, Ray Gilbert"
piece = "Bossa"
copyright = "1965, Ipanema Music. Used By Permission."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "18294374-a26f-11df-a5f0-0019d11e5a41"
structure = "AAB"
location = "rbk1:329,nrbk1:250"
idyoutuberemark1 = "Joe Henderson accompanied by guitar doing Bossa..."
idyoutube1 = "rJxHFW2S-Eo"
idyoutuberemark2 = "Astrud Gilberto (original Bossa Style with Orchestra)"
idyoutube2 = "BwP0eIRU-dQ"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Once-I-Loved-lyrics-Ella-Fitzgerald/24CD6F6E245519E348256AAB0009C557"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1965, Ipanema Music. Used By Permission."
fullpoet = "Lyrics by Vinicius DeMoraes, Ray Gilbert"
fullcomposer = "Music by Antonio Carlos Jobim"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
