# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Opus One"
style = "Jazz"
composer = "Sy Oliver"
poet = "Sy Oliver"
piece = "Moderate Jump Tempo"
copyright = "1943 (Renewed) Embassy Music Corporation, New York."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "31cf66b6-11b8-11e4-bcfe-f76051fd87b1"
structure = "AABA"
structureremark = "The A's are just a little bit different"
location = "jfb:291"
idyoutuberemark1 = "Nat King Cole swings"
idyoutube1 = "a33vdj7zoB0"
idyoutuberemark2 = "Tommy Dorsey's Orchestra swings"
idyoutube2 = "rV9LhjTr5Bc"
lyricsurl = "http://www.songlyrics.com/the-mills-brothers/opus-one-lyrics/"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1943 (Renewed) Embassy Music Corporation, New York."
fullcomposer = "Lyrics and Music by Sy Oliver"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
