# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Polka Dots And Moonbeams"
style = "Jazz"
composer = "Jimmy Van Heusen"
poet = "Johnny Burke"
piece = "Slowly, with expression"
copyright = "1940 by ARC Music Corp., now Bourne Co. and Dorsey Bros."
copyrightextra = "Music, Division of Music Sales Corporation"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "60170b42-46e0-11e0-bf54-0019d11e5a41"
structure = "AABA"
location = "jfb:304"
idyoutube1 = "4NTxWQfMSsA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1940 by ARC Music Corp., now Bourne Co. and Dorsey Bros."
fullpoet = "Lyrics by Johnny Burke"
fullcomposer = "Music by Jimmy Van Heusen"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
