# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Red Sails In The Sunset"
style = "Jazz"
composer = "Hugh Williams"
poet = "Jimmy Kennedy"
piece = "Slowly"
copyright = "1935 The Peter Maurice Music Co. Ltd., London, England"
copyrightextra = "United Sates Copyright Renewed and Assigned to Sharpiro, Bernstein & Co., Inc."
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "2507f6ec-da80-11e3-9bfd-ff436f70a1a7"
structure = "AABA"
location = "jfb:313"
idyoutuberemark1 = "Nat King Cole in a classic..."
idyoutube1 = "HLQZZoAkdig"
idyoutuberemark2 = "The Beatles?!?"
idyoutube2 = "b_Xg_md46Sw"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Red-Sails-In-the-Sunset-lyrics-Nat-King-Cole/F51AC099651BC18A48256AF1000B7499"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1935 The Peter Maurice Music Co. Ltd., London, England"
fullpoet = "Lyrics by Jimmy Kennedy"
fullcomposer = "Music by Hugh Williams"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
