# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Robbin's nest"
style = "Jazz"
composer = "Sir Charles Thompson, Jean-Baptiste \\\"Illinois\\\" Jacquet"
piece = "Medium Swing"
copyright = "1947, 1948, 1951, 1952 (Renewed 1975, 1976, 1979, 1980) Atlantic Music Corp"
typesetter = "Samuel Tardieu <sam@rfc1149.net>"
completion = "5"
uuid = "c921579e-a26e-11df-9a5c-0019d11e5a42"
structure = "AABA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1947, 1948, 1951, 1952 (Renewed 1975, 1976, 1979, 1980) Atlantic Music Corp"
fullpoet = ""
fullcomposer = "Music by Sir Charles Thompson, Jean-Baptiste \\\"Illinois\\\" Jacquet"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
