# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "'Round Midnight"
style = "Jazz"
composer = "Cootie Williams, Thelonious Monk"
poet = "Bernie Hanighen"
piece = "Ballad"
copyright = "1944 (Renewed) Warner Bros. Inc. and Thelonian Music"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "1c99c334-a26f-11df-b3cb-0019d11e5a41"
structure = "AABA"
location = "rbk1:364,jfb:322"
idyoutuberemark1 = "Ella's vocal version"
idyoutube1 = "DEaDj6TXiQQ"
idyoutuberemark2 = "Monk. What can I say?"
idyoutube2 = "OMmeNsmQaFw"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Round-Midnight-lyrics-Ella-Fitzgerald/F7F9D0761ABE750348256AAB0009FEEA"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "'Round Midnight / Cootie Williams, Thelonious Monk, Bernie Hanighen"
copyright = "Copyright © 1944 (Renewed) Warner Bros. Inc. and Thelonian Music"
fullpoet = "Lyrics by Bernie Hanighen"
fullcomposer = "Music by Cootie Williams, Thelonious Monk"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
