# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Solar"
style = "Jazz"
composer = "Miles Davis"
piece = "Jazz"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "841f9004-4477-11e2-acde-078065be2912"
structure = "A"
structureremark = "The 12 bars have a kind of blues structure feel to them"
location = "rbk1:386"
idyoutuberemark1 = "Metheny/Holland/Hancock/DeJohnette kickass performance"
idyoutube1 = "FAYt3a-c_k0"
idyoutuberemark2 = "Classic miles davis"
idyoutube2 = "9GADuMRXMRw"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Solar / Miles Davis"
copyright = "-- help me fill it out this copyright notice --"
fullpoet = ""
fullcomposer = "Music by Miles Davis"

[versions.Real]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
