# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Ccb"

[attributes]
title = "Somewhere, Over The Rainbow"
style = "Jazz"
composer = "Harold Arlen"
poet = "Edgar Yipsel 'Yip' Harburg"
piece = "Ballad"
copyright = "Musicopy"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "f046f51c-ed4d-11e3-9d71-67b6b025e741"
structure = "AABA"
location = "cc:209,file:over_the_rainbow.pdf,nrbk3:287-288"
idyoutuberemark1 = "Keith Jarret solo"
idyoutube1 = "eq0EWNuR1H8"
idyoutuberemark2 = "Original Judy Garland version"
idyoutube2 = "PSZxmZmBfnU"
idyoutuberemark3 = "Keith Jarret kills them"
idyoutube3 = "u3eH6VW6Chc"
idyoutuberemark4 = "The original Judy Garland version"
idyoutube4 = "1HRa4X07jdE"
lyricsurl = "http://www.stlyrics.com/lyrics/thewizardofoz/somewhereovertherainbow.htm"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = true
idyoutube3 = true
idyoutuberemark4 = true
idyoutube4 = true
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Somewhere, Over The Rainbow / Harold Arlen, Edgar Yipsel 'Yip' Harburg"
copyright = "Copyright © Musicopy"
fullpoet = "Lyrics by Edgar Yipsel 'Yip' Harburg"
fullcomposer = "Music by Harold Arlen"

[versions.Ccb]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Wikifonia]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
