# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Real"

[attributes]
title = "Someday My Prince Will Come"
style = "Jazz"
composer = "Frank Churchill"
poet = "Larry Morey"
piece = "Med. Jazz Waltz"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "4933391e-ee10-11e0-b804-0019d11e5a41"
structure = "ABAC"
structureremark = "This could be thought of as AB as well"
location = "rbk1:388"
idyoutuberemark1 = "Miles"
idyoutube1 = "Lo18F5ObPng"
idyoutuberemark2 = "the great Bill Evans"
idyoutube2 = "zYpKNM1Yi5o"
idyoutuberemark3 = "and Bill again"
idyoutube3 = "KUT06K5eGz4"
lyricsurl = "http://artists.letssingit.com/disney-lyrics-someday-my-prince-will-come-31rjgwv"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = true
idyoutube3 = true
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Someday My Prince Will Come / Frank Churchill, Larry Morey"
copyright = "-- help me fill it out this copyright notice --"
fullpoet = "Lyrics by Larry Morey"
fullcomposer = "Music by Frank Churchill"

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = true
doPrep = false
doOwn = false
