# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Strangers In The Night"
style = "Jazz"
composer = "Bert Kaempfert"
poet = "Charles Singleton, Eddie Snyder"
piece = "Moderately Slow"
copyright = "1966 by Champion Music Corporation and Screen Gems-EMI"
copyrightextra = "Sole Selling Agent MCA MUSIC PUBLISHING, A Division of MCA Inc., New York, NY"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "2af3e35c-e252-11e3-abb7-932771d3c7a0"
structure = "AA'BA"
location = "jfb:364-365"
idyoutuberemark1 = "Cannonical version by Frank"
idyoutube1 = "hlSbSKNk9f0"
idyoutuberemark2 = "Another version by Frank"
idyoutube2 = "nHuko5BCFzA"
lyricsurl = "http://www.lyricsfreak.com/f/frank+sinatra/strangers+in+the+night_20056148.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Strangers In The Night / Bert Kaempfert, Charles Singleton, Eddie Snyder"
copyright = "Copyright © 1966 by Champion Music Corporation and Screen Gems-EMI"
fullpoet = "Lyrics by Charles Singleton, Eddie Snyder"
fullcomposer = "Music by Bert Kaempfert"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
