# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Unknown"

[attributes]
title = "Take Five"
style = "Jazz"
composer = "Paul Desmond"
piece = "Moderately"
copyright = "1960 (Renewed) Desmond Music Company (U.S.A.) and Derry Music Company (Canada)"
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "86e17438-da80-11e3-9f6f-832caca8efee"
structure = "ABA"
location = "rbk1:420"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1960 (Renewed) Desmond Music Company (U.S.A.) and Derry Music Company (Canada)"
fullpoet = ""
fullcomposer = "Music by Paul Desmond"

[versions.Unknown]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
