# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Unknown"

[attributes]
title = "The Nearness Of You"
style = "Jazz"
subtitle = "From the Paramount Picture 'Romance in the Dark'"
composer = "Hoagy Carmichael"
poet = "Ned Washington"
piece = "Slowly"
copyright = "1937, 1940 Famous Music Corporation"
copyrightextra = "Renewed 1964, 1967"
typesetter = "Jordan Eldredge <jordan@jordaneldredge.com>"
completion = "5"
uuid = "aeb48162-da80-11e3-9daf-67e95f938714"
structure = "AABA"
location = "rbk2:261"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "The Nearness Of You / Hoagy Carmichael, Ned Washington"
copyright = "Copyright © 1937, 1940 Famous Music Corporation"
fullpoet = "Lyrics by Ned Washington"
fullcomposer = "Music by Hoagy Carmichael"

[versions.Unknown]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
