# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "The Girl From Ipanema"
style = "Jazz"
subtitle = "Garota De Ipanema"
composer = "Antonio Carlos Jobim"
poet = "Vincius De Moraes, Norman Gimbel"
piece = "Moderate Bossa Nova"
copyright = "1963, Antonio Carlos Jobim and Vincius De Moraes, Brazil"
copyrightextra = "Sole Selling Agent Duchess Music Corporation (MCA), New York, NY for all. English speaking countries"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "2c3b337c-a26f-11df-b7d1-0019d11e5a41"
structure = "AABA"
location = "rbk1:171,jfb:132"
idyoutuberemark1 = "Tom Jobim and Joan Gilberto"
idyoutube1 = "DmV0TcTNJ3o"
idyoutuberemark2 = "Frank!"
idyoutube2 = "NldPFVKYmiw"
lyricsurl = "http://www.lyricsfreak.com/f/frank+sinatra/girl+from+ipanema+the_10121534.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "Copyright © 1963, Antonio Carlos Jobim and Vincius De Moraes, Brazil"
fullpoet = "Lyrics by Vincius De Moraes, Norman Gimbel"
fullcomposer = "Music by Antonio Carlos Jobim"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
