# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "There Will Never Be Another You"
style = "Jazz"
composer = "Harry Warren"
poet = "Mack Gordon"
piece = "Easy Swing"
copyright = "1942, 1987 Twentieth Century Music Corporation"
copyrightextra = "Renewed 1970 Twentieth Century Music Corporation. All Rights Controlled by Morley Music Co. International Copyright Secured. All Rights Reserved."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "e30e1074-eaf3-11e0-a377-0019d11e5a41"
structure = "AB"
structureremark = "the structure of this tune could also be thought of ABAC since in the AB interpretation the first 8 bars of the A and B part are identical."
location = "jfb:384,rbk1:426"
idyoutube1 = "kh_NnsbIqNQ"
idyoutube2 = "Til3lV_ItZE"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = true
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "There Will Never Be Another You / Harry Warren, Mack Gordon"
copyright = "Copyright © 1942, 1987 Twentieth Century Music Corporation"
fullpoet = "Lyrics by Mack Gordon"
fullcomposer = "Music by Harry Warren"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false

[versions.Real]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
