# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "They Can't Take That Away From Me"
style = "Jazz"
composer = "George Gershwin"
poet = "Ira Gershwin"
piece = "Moderately"
copyright = "1937 by Gershwin Publishing Corporation"
copyrightextra = "Copyright renewed, Assigned to Chappell & Co., Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "d0904c80-d84b-11e3-b741-dbf5614f4f33"
structure = "AABA"
location = "jfb:390"
idyoutuberemark1 = "Louis and Ella in a great performance"
idyoutube1 = "ExmoiGZuiFQ"
idyoutuberemark2 = "Tony Bennett and Elvis Constello..."
idyoutube2 = "x6uDp5lYPzs"
lyricsurl = "http://www.lyrics007.com/Ella%20Fitzgerald%20Lyrics/They%20Can%27t%20Take%20That%20Away%20From%20Me%20Lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "They Can't Take That Away From Me / George Gershwin, Ira Gershwin"
copyright = "Copyright © 1937 by Gershwin Publishing Corporation"
fullpoet = "Lyrics by Ira Gershwin"
fullcomposer = "Music by George Gershwin"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
