# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "Waltz For Debby"
style = "Jazz"
composer = "Bill Evans"
poet = "Gene Lees"
piece = "Moderately, in one"
copyright = "1964 and 1965 Acom Music Corp., New York, NY."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "010d881c-e348-11e3-bd2b-af99bf9a3980"
structure = "AABA"
location = "jfb:414"
idyoutuberemark1 = "Bill Evans in great form"
idyoutube1 = "dH3GSrCmzC8"
idyoutuberemark2 = "Bill with Tony Bennett"
idyoutube2 = "lsb8mYrYycE"
lyricsurl = "http://www.azlyrics.com/lyrics/tonybennett/waltzfordebby.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "Waltz For Debby / Bill Evans, Gene Lees"
copyright = "Copyright © 1964 and 1965 Acom Music Corp., New York, NY."
fullpoet = "Lyrics by Gene Lees"
fullcomposer = "Music by Bill Evans"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = true
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
