# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Aebersold"

[attributes]
title = "Watermelon Man"
style = "Jazz"
composer = "Herbie Hancock"
piece = "16-Bar Blues"
copyright = "1962, 1963 & 1965 By Hancock Music Co., New York, NY"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "359f7428-a26f-11df-ad8c-0019d11e5a41"
structure = "16 bar Blues"
location = "rbk3:334"
idyoutube1 = "4z8Rt4nvd-I"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1962, 1963 & 1965 By Hancock Music Co., New York, NY"
fullpoet = ""
fullcomposer = "Music by Herbie Hancock"

[versions.Aebersold]
doChords = true
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
