# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "What A Wonderful World"
style = "Jazz"
composer = "George David Weiss, Bob Thiele"
poet = "George David Weiss, Bob Thiele"
piece = "Slowly"
copyright = "1967 by Range Road Music Inc. and Quartet Music Inc."
copyrightextra = "All rights administered by Hudson Bay Music, Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "39de7d2c-a26f-11df-8dbc-0019d11e5a41"
structure = "AABA"
location = "jfb:422-423"
idyoutuberemark1 = "Orchestral version from the film score of 'Meet Joe Black'"
idyoutube1 = "Qhrpc9FFFAI"
idyoutuberemark2 = "Louis in the classic version"
idyoutube2 = "m5TwT69i1lU"
lyricsurl = "http://www.lyrics007.com/Louis%20Armstrong%20Lyrics/What%20A%20Wonderful%20World%20Lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = true
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "What A Wonderful World / George David Weiss, Bob Thiele"
copyright = "Copyright © 1967 by Range Road Music Inc. and Quartet Music Inc."
fullcomposer = "Lyrics and Music by George David Weiss, Bob Thiele"
fullpoet = ""

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
