# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Fake"

[attributes]
title = "What A Diff'rence A Day Made"
style = "Jazz"
composer = "Maria Grever"
poet = "Stanley Adams"
piece = "Relaxed"
copyright = "1934 by Edward B. Marks Music Company. Copyright Renewed."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "d28e02f4-2218-11e4-870b-bfbfa80d68bd"
structure = "ABAC"
location = "jfb:422"
idyoutuberemark1 = "Dinah Washington in a classic performance"
idyoutube1 = "OmBxVfQTuvI"
idyoutuberemark2 = "Jamie Cullum vocal+piano"
idyoutube2 = "NzS4ygeE1oQ"
lyricsurl = "http://www.azlyrics.com/lyrics/reneeolstead/whatadifferenceadaymakes.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = true
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "What A Diff'rence A Day Made / Maria Grever, Stanley Adams"
copyright = "Copyright © 1934 by Edward B. Marks Music Company. Copyright Renewed."
fullpoet = "Lyrics by Stanley Adams"
fullcomposer = "Music by Maria Grever"

[versions.Fake]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = true
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
