# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "My"

[attributes]
heb = true
title = "נח"
style = "Israeli"
composer = "מתי כספי"
poet = "יורם טהרלב"
piece = "סמבה"
singer = "מתי כספי"
typesetter = "מרק ולצר <mark.veltzer@gmail.com>"
completion = "5"
uuid = "702eab24-e8ce-11e2-91c8-5b1ff4f22893"
structure = "A"
idyoutuberemark1 = "Mati Caspi in the original performance"
idyoutube1 = "Eiae247OZXI"
lyricsurl = "http://shironet.mako.co.il/artist?type=lyrics&lang=1&prfid=688&wrkid=2292&gclid=CLiirsj_o7gCFci23godXw0A8w"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = true
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = true
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = true
structureremark = false
location = false
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
tocname = "נח / מתי כספי, יורם טהרלב"
copyright = "-- עיזרו לי למלא את שורת זכויות היוצרים הזו --"
fullpoet = "מלים: יורם טהרלב"
fullcomposer = "לחן: מתי כספי"

[versions.My]
doChords = true
doVoice = true
doLyrics = true
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = true
doPrep = false
doOwn = false
