[mypy]
mypy_path = src:python:scripts
explicit_package_bases = True
namespace_packages = True

# Third-party libraries and local modules without type stubs.
# In mypy, the pattern `foo.*` matches `foo` itself as well as its submodules.

[mypy-accelerate.*]
ignore_missing_imports = True

[mypy-anthropic.*]
ignore_missing_imports = True

[mypy-azure.*]
ignore_missing_imports = True

[mypy-bitmath.*]
ignore_missing_imports = True

[mypy-bleach.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-browser_cookie3.*]
ignore_missing_imports = True

[mypy-browsercookie.*]
ignore_missing_imports = True

[mypy-cmd2.*]
ignore_missing_imports = True

[mypy-colorama.*]
ignore_missing_imports = True

[mypy-colored.*]
ignore_missing_imports = True

[mypy-confluent_kafka.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-daemon.*]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-dialog.*]
ignore_missing_imports = True

[mypy-dispy.*]
ignore_missing_imports = True

[mypy-django.db.*]
ignore_missing_imports = True

[mypy-django.urls.*]
ignore_missing_imports = True

[mypy-dnslib.*]
ignore_missing_imports = True

[mypy-docker.*]
ignore_missing_imports = True

[mypy-download.*]
ignore_missing_imports = True

[mypy-elasticsearch.*]
ignore_missing_imports = True

[mypy-exif.*]
ignore_missing_imports = True

[mypy-exifread.*]
ignore_missing_imports = True

[mypy-exiftool.*]
ignore_missing_imports = True

[mypy-fake_useragent.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-fastparquet.*]
ignore_missing_imports = True

[mypy-fire.*]
ignore_missing_imports = True

[mypy-flask_limiter.*]
ignore_missing_imports = True

[mypy-flask_restful.*]
ignore_missing_imports = True

[mypy-flaskext.mysql.*]
ignore_missing_imports = True

[mypy-flax.*]
ignore_missing_imports = True

[mypy-fluidsynth.*]
ignore_missing_imports = True

[mypy-furl.*]
ignore_missing_imports = True

[mypy-gdata.*]
ignore_missing_imports = True

[mypy-gevent.*]
ignore_missing_imports = True

[mypy-github.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-google_auth_oauthlib.*]
ignore_missing_imports = True

[mypy-googleapiclient.*]
ignore_missing_imports = True

[mypy-humanize.*]
ignore_missing_imports = True

[mypy-hurry.filesize.*]
ignore_missing_imports = True

[mypy-imageio.*]
ignore_missing_imports = True

[mypy-imdb.*]
ignore_missing_imports = True

[mypy-inject.*]
ignore_missing_imports = True

[mypy-jax.*]
ignore_missing_imports = True

[mypy-jaxlib.*]
ignore_missing_imports = True

[mypy-jenkins.*]
ignore_missing_imports = True

[mypy-jq.*]
ignore_missing_imports = True

[mypy-jsonpickle.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-keras.*]
ignore_missing_imports = True

[mypy-kubernetes.*]
ignore_missing_imports = True

[mypy-lmdb.*]
ignore_missing_imports = True

[mypy-logging_tree.*]
ignore_missing_imports = True

[mypy-luigi.*]
ignore_missing_imports = True

[mypy-lupa.*]
ignore_missing_imports = True

[mypy-magic.*]
ignore_missing_imports = True

[mypy-mako.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-MediaInfoDLL3.*]
ignore_missing_imports = True

[mypy-mingus.*]
ignore_missing_imports = True

[mypy-mpmath.*]
ignore_missing_imports = True

[mypy-msrest.*]
ignore_missing_imports = True

[mypy-multipart.*]
ignore_missing_imports = True

[mypy-mysql.*]
ignore_missing_imports = True

[mypy-MySQLdb.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-oauth2client.*]
ignore_missing_imports = True

[mypy-openai.*]
ignore_missing_imports = True

[mypy-openshift.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-paramiko.*]
ignore_missing_imports = True

[mypy-passpy.*]
ignore_missing_imports = True

[mypy-piexif.*]
ignore_missing_imports = True

[mypy-pigments.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-pkg_resources.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-pluginbase.*]
ignore_missing_imports = True

[mypy-pornhub_api.*]
ignore_missing_imports = True

[mypy-pptx.*]
ignore_missing_imports = True

[mypy-progressbar.*]
ignore_missing_imports = True

[mypy-prompt_toolkit.*]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-ptterm.*]
ignore_missing_imports = True

[mypy-pyanyzip.*]
ignore_missing_imports = True

[mypy-pyapikey.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-pyclassifiers.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-pydmt.*]
ignore_missing_imports = True

[mypy-pyeventroute.*]
ignore_missing_imports = True

[mypy-pyfakeuse.*]
ignore_missing_imports = True

[mypy-pygame.*]
ignore_missing_imports = True

[mypy-pygments.*]
ignore_missing_imports = True

[mypy-pygooglehelper.*]
ignore_missing_imports = True

[mypy-pyinotify.*]
ignore_missing_imports = True

[mypy-pylab.*]
ignore_missing_imports = True

[mypy-pylogconf.*]
ignore_missing_imports = True

[mypy-pymount.*]
ignore_missing_imports = True

[mypy-pymysql.*]
ignore_missing_imports = True

[mypy-pypathutil.*]
ignore_missing_imports = True

[mypy-pypipegzip.*]
ignore_missing_imports = True

[mypy-PyQt5.*]
ignore_missing_imports = True

[mypy-PyRSS2Gen.*]
ignore_missing_imports = True

[mypy-pyslowloris.*]
ignore_missing_imports = True

[mypy-pytconf.*]
ignore_missing_imports = True

[mypy-pyvardump.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy-ruamel.*]
ignore_missing_imports = True

[mypy-scapy.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-scrapy.*]
ignore_missing_imports = True

[mypy-seaborn.*]
ignore_missing_imports = True

[mypy-secretstorage.*]
ignore_missing_imports = True

[mypy-selenium.*]
ignore_missing_imports = True

[mypy-seleniumwire.*]
ignore_missing_imports = True

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-simpleaudio.*]
ignore_missing_imports = True

[mypy-simpleparse.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-sortedcontainers.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-sultan.*]
ignore_missing_imports = True

[mypy-svgwrite.*]
ignore_missing_imports = True

[mypy-sympy.*]
ignore_missing_imports = True

[mypy-tensorflow.*]
ignore_missing_imports = True

[mypy-texttable.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True

[mypy-tornado.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-tsv.*]
ignore_missing_imports = True

[mypy-twisted.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True

[mypy-webdriver_manager.*]
ignore_missing_imports = True

[mypy-whisper.*]
ignore_missing_imports = True

[mypy-yapsy.*]
ignore_missing_imports = True

[mypy-youtube_dl.*]
ignore_missing_imports = True

[mypy-yt_dlp.*]
ignore_missing_imports = True
