# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "My"

[attributes]
title = "Jazz chords on the major scale"
style = "Jazz"
piece = "Upbeat Jazz"
copyright = "-- no copyright notice for study materials --"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "4"
uuid = "ffbec224-36a6-11e0-aecb-0019d11e5a41"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = false
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = false
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Jazz chords on the major scale"
copyright = "Copyright © -- no copyright notice for study materials --"
fullpoet = ""
fullcomposer = ""

[versions.My]
doChords = false
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
