# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Epdf0"

[attributes]
title = "Sonata III"
style = "Classical"
composer = "Wolfgang Amadeus Mozart"
copyright = "1918, G.Schirmer Inc."
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "0"
uuid = "744f61d8-a26f-11df-b6b1-0019d11e5a41"
remark = "Edited, revised and fingered by Richard Epstein"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = false
piece = false
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = true
idyoutuberemark1 = false
idyoutube1 = false
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
copyright = "Copyright © 1918, G.Schirmer Inc."
fullpoet = ""
fullcomposer = "Music by Wolfgang Amadeus Mozart"

[versions.Epdf0]
doChords = false
doVoice = true
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
