# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "Own"

[attributes]
title = "Prelude and Fugue No. 1 in C major"
style = "Classical"
subtitle = "Well-Tempered Clavier, Book 1"
composer = "Johann Sebastian Bach (1685-1750)"
piece = "BWV 846"
copyright = "Public Domain"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "562ae904-a664-11df-9e85-0019d11e5a41"
remark = "Taken from Shlomo Gronichs book"
idyoutube1 = "0KQW2YnCUrE"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = true
subsubtitle = false
composer = true
poet = false
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = true
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = true
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = false
wiki = false

[computed]
tocname = "Prelude and Fugue No. 1 in C major / Johann Sebastian Bach (1685-1750)"
copyright = "Copyright © Public Domain"
fullpoet = ""
fullcomposer = "Music by Johann Sebastian Bach (1685-1750)"

[versions.Own]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = true
