# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "DontMatter"

[attributes]
title = "Days Like This"
style = "Rock"
composer = "Van Morrison"
poet = "Van Morrison"
piece = "Med. Ballad"
album = "Days Like This/1995"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "6437a34a-3bd4-11e2-9e13-9f845e169c9b"
remark = "This is the right scale"
idyoutuberemark1 = "Original video clip"
idyoutube1 = "BteIwbKU_iQ"
lyricsurl = "http://www.lyricsfreak.com/v/van+morrison/days+like+this_20142994.html"
wiki = "Days_Like_This_(song)"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = true
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = true
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = true

[computed]
tocname = "Days Like This / Van Morrison"
copyright = "-- help me fill it out this copyright notice --"
fullcomposer = "Lyrics and Music by Van Morrison"
fullpoet = ""

[versions.DontMatter]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = true
doExtra = false
doPrep = false
doOwn = true
