# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "DontMatter"

[attributes]
title = "Lucky Man"
style = "Rock"
composer = "Greg Lake"
poet = "Greg Lake"
piece = "Med. Ballad"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "a68bcbbc-c8ae-11e0-8fa9-0019d11e5a41"
remark = "The D scale is the one used in the original version (Mark Veltzer,17/8/11)"
idyoutube1 = "5x6uQ6yZsOY"
lyricsurl = "http://www.sing365.com/music/lyric.nsf/Lucky-Man-lyrics-Emerson-Lake-Palmer/13302F99F6B11DEC48256AB8002432F8"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = false
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = true
idyoutuberemark1 = false
idyoutube1 = true
idyoutuberemark2 = false
idyoutube2 = false
idyoutuberemark3 = false
idyoutube3 = false
idyoutuberemark4 = false
idyoutube4 = false
idyoutuberemark5 = false
idyoutube5 = false
idyoutuberemark6 = false
idyoutube6 = false
lyricsurl = true
wiki = false

[computed]
copyright = "-- help me fill it out this copyright notice --"
fullcomposer = "Lyrics and Music by Greg Lake"
fullpoet = ""

[versions.DontMatter]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = true
doExtra = false
doPrep = false
doOwn = true
