# extracted from the mako Vars part by scripts/convert_to_tera.py
default_version = "My"

[attributes]
title = "Shape of My Heart"
style = "Pop"
composer = "Sting, Dominic Miller"
poet = "Sting"
piece = "Med. Ballad"
singer = "Sting"
typesetter = "Mark Veltzer <mark.veltzer@gmail.com>"
completion = "5"
uuid = "677fee0a-a26f-11df-bd2c-0019d11e5a41"
idyoutuberemark1 = "Leon the professional clip...:)"
idyoutube1 = "_0J0toYZB6Q"
idyoutuberemark2 = "Another one from Leon...:)"
idyoutube2 = "nVYFOlVB-Uo"
idyoutuberemark3 = "And another one from Leon...:)"
idyoutube3 = "P_1orNvO6Xk"
idyoutuberemark4 = "And another one from Leon...:)"
idyoutube4 = "locIxsfpgp4"
idyoutuberemark5 = "Sting and Dominic with nylon guitar"
idyoutube5 = "037uSAIahho"
idyoutuberemark6 = "Orignal video in the studio"
idyoutube6 = "qZ22i7QllO8"
lyricsurl = "http://www.lyrics007.com/Sting%20Lyrics/Shape%20Of%20My%20Heart%20Lyrics.html"

[has]
doChords = false
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = false
doExtra = false
doPrep = false
doOwn = false
render = false
heb = false
dedication = false
title = true
style = true
subtitle = false
subsubtitle = false
composer = true
poet = true
piece = true
singer = true
arranger = false
album = false
opus = false
instrument = false
copyright = false
copyrightextra = false
copyrightextraextra = false
typesetter = true
completion = true
dontimport = false
uuid = true
structure = false
structureremark = false
location = false
remark = false
idyoutuberemark1 = true
idyoutube1 = true
idyoutuberemark2 = true
idyoutube2 = true
idyoutuberemark3 = true
idyoutube3 = true
idyoutuberemark4 = true
idyoutube4 = true
idyoutuberemark5 = true
idyoutube5 = true
idyoutuberemark6 = true
idyoutube6 = true
lyricsurl = true
wiki = false

[computed]
copyright = "-- help me fill it out this copyright notice --"
fullpoet = "Lyrics by Sting"
fullcomposer = "Music by Sting, Dominic Miller"

[versions.My]
doChords = true
doVoice = false
doLyrics = false
doLyricsmore = false
doLyricsmoremore = false
doChordBars = false
doGuitar = true
doExtra = true
doPrep = false
doOwn = false
